package com.itexus.test

interface SettingsFeatureCoordinator {
    fun navigateBackward()
    fun navigateBackFromPersonalInfo()
    fun navigateBackFromBankAccounts()
    fun navigateBackFromLimits()
    fun navigateToChangePhoneNumber(phoneNumber: String)
    fun navigateToChangeEmail(email: String)
    fun navigateBackToPersonalInfo()
    fun navigateToChangePassword()
    fun navigateToChangePin()
    fun navigateToTryAgain()
    fun navigateToCreateNewPassword()
    fun navigateToConfirmEmailSettingsScreen(email: String, oldEmail: String)
    fun navigateBackFromConfirmEmailSettingsScreen(email: String, oldEmail: String)
    fun navigateToPhoneNumberConfirmation(phoneNumber: String, oldPhoneNumber: String)
    fun navigateBackFromPhoneConfirmation(phoneNumber: String, oldPhoneNumber: String)
    fun navigateToPersonalInfoAfterPhoneNumberChanged()
    fun navigateToFAQ()
    fun navigateToLimits()
    fun navigateToProfile()
    fun navigateToSecurity()
    fun navigateToTermsNConditions()
    fun navigateToBankAccounts()
    fun navigateToWelcomeScreen()
    fun navigateToErrorScreen()
    fun handleNoInternetConnectionTryAgain()
    fun navigateToBalancesFromLimits()
    fun navigateToKYC(token: String)
    fun navigateToUserBlocked()
    fun navigateToAllowCameraAccess()
    fun navigateToDeepLinksTryAgain()
}